version: '3.7'

services:
  postgres:
    image: postgres:latest
    container_name: "postgres-store"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: store
    ports:
      - "5432:5432"
    volumes:
      - store_volume:/var/lib/postgresql/data

volumes:
  store_volume:
